language: java
jdk: oraclejdk8

branches:
  except:
    - master

cache:
  directories:
  - $HOME/.m2/repository

install: mvn install

addons:
  sonarcloud:
    organization: "serbroda-github"
    token:
      secure: e0624c074cc2912e0a56aad2df374638bbc29bed
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar